---
- name: Install nginx
  hosts: webservers
  become: true

  tasks:

  - name: update packages
    apt:
      update_cache: yes
  - name: Install nginx
    apt:
      name: nginx
      state: present
      update_cache: true
    notify:
    - start nginx

  - name: start nginx
    service:
      name: nginx
      enabled: yes
      state: restarted
  handlers:
  - name: start nginx
    service:
      name: nginx
      state: restarted
      enabled: yes

       # - name: Insert Index Page
       #   template:
       #     src: index.html
       #     dest: /usr/share/nginx/html/index.html